# Master configuration
replicaCount: 1 # Single master node

# Image configuration
image:
  repository: openbiocure/spark-arm
  tag: v0.3
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 7077
  uiPort: 8080

# Storage configuration
storage:
  className: local-path
  size: 10Gi

# Worker configuration
worker:
  replicaCount: 2 # Ensuring 2 worker replicas
  cores: "2"
  memory: "2048m"
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "1Gi"

# Resource limits and requests for master
resources:
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "1"
    memory: "1Gi"

# ServiceAccount configuration
serviceAccount:
  create: true
  name: spark
  automount: true
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
