# Release name and namespace
nameOverride: ""
fullnameOverride: ""
namespace: spark

# Master configuration
master:
  enabled: true
  resources:
    limits:
      cpu: "1"
      memory: "1Gi"
    requests:
      cpu: "500m"
      memory: "512Mi"
  env:
    SPARK_MASTER_PORT: "7077"
    SPARK_MASTER_WEBUI_PORT: "8080"

# Worker configuration
worker:
  enabled: true
  replicaCount: 2
  cores: "2"
  memory: "2048m"
  resources:
    limits:
      cpu: "2"
      memory: "2Gi"
    requests:
      cpu: "1"
      memory: "1Gi"
  env:
    SPARK_MASTER_PORT: "7077"
    SPARK_WORKER_CORES: "2"
    SPARK_WORKER_MEMORY: "2048m"

# Image configuration
image:
  repository: ghcr.io/openbiocure/spark-arm
  tag: sha-feab3a9
  pullPolicy: IfNotPresent

# Service configuration
service:
  type: ClusterIP
  port: 7077
  uiPort: 8080

# Storage configuration
storage:
  className: local-path
  size: 10Gi
  accessMode: ReadWriteOnce

# ServiceAccount configuration
serviceAccount:
  create: true
  name: spark
  automount: true
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    traefik.ingress.kubernetes.io/router.tls: "true"
    kubernetes.io/ingress.class: traefik
  hosts:
    - host: "spark.cluster.local"
      paths:
        - path: /
          pathType: Prefix

# Traefik specific configuration
traefik:
  enabled: true
  dashboard:
    enabled: true
    domain: "spark-dashboard.cluster.local"
  ssl:
    enabled: true
    existingSecret: ""
    createSecret: false
    cert: ""
    key: ""
    certManager:
      enabled: true
      issuerName: "letsencrypt-prod"
      issuerKind: "ClusterIssuer"
  middlewares:
    auth:
      enabled: false
      type: "basicAuth"
      users: []
    cors:
      enabled: false
      allowedOrigins: ["*"]
      allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    rateLimit:
      enabled: false
      average: 100
      burst: 50

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
