# Master configuration
replicaCount: 1 # Single master node

# Image configuration
image:
  repository: openbiocure/spark-arm
  tag: v0.2
  pullPolicy: Always

# Service configuration
service:
  type: ClusterIP
  port: 7077
  uiPort: 8080

# Worker configuration
worker:
  replicaCount: 2
  cores: "2"
  memory: "2g"
  resources:
    limits:
      cpu: 2000m
      memory: 2560Mi
    requests:
      cpu: 1000m
      memory: 2048Mi

# Resource limits and requests for master
resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 1536Mi

# ServiceAccount configuration
serviceAccount:
  create: true
  name: spark
  automount: true
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
