apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "spark-arm.fullname" . }}-hive
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: hive
spec:
  serviceName: {{ include "spark-arm.fullname" . }}-hive
  replicas: {{ .Values.hive.replicaCount }}
  selector:
    matchLabels:
      {{- include "spark-arm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: hive
  template:
    metadata:
      labels:
        {{- include "spark-arm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: hive
    spec:
      serviceAccountName: spark
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      initContainers:
        - name: init-chown-data
          image: "{{ .Values.hive.image.repository }}:{{ .Values.hive.image.tag }}"
          command: 
            - sh
            - -c
            - |
              chown -R 1000:1000 \
                /opt/hive/logs \
                /opt/hive/warehouse \
                /opt/hive/scratch
          securityContext:
            runAsUser: 0  # Run as root to be able to chown
          volumeMounts:
            - name: hive-logs
              mountPath: /opt/hive/logs
            - name: hive-warehouse
              mountPath: /opt/hive/warehouse
            - name: hive-scratch
              mountPath: /opt/hive/scratch
      containers:
        - name: hive
          image: "{{ .Values.hive.image.repository }}:{{ .Values.hive.image.tag }}"
          imagePullPolicy: {{ .Values.hive.image.pullPolicy }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            # PostgreSQL Environment Variables
            # todo: fix this
            - name: POSTGRES_HOST
              value: "172.16.14.112"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "hive"
            - name: POSTGRES_PASSWORD
              value: "hive"
            - name: POSTGRES_DB
              value: "hive"
            # PostgreSQL Connection
            - name: HIVE_METASTORE_DB_HOST
              value: "172.16.14.112"
            - name: HIVE_METASTORE_DB_PORT
              value: "5432"
            - name: HIVE_METASTORE_DB_USER
              value: "hive"
            - name: HIVE_METASTORE_DB_PASSWORD
              value: "hive"
            - name: HIVE_METASTORE_DB_NAME
              value: "hive"
            # Hive Metastore
            - name: HIVE_METASTORE_URI
              value: "thrift://0.0.0.0:{{ .Values.hive.service.metastorePort }}"
            - name: HIVE_METASTORE_HOST
              value: "0.0.0.0"
            - name: HIVE_METASTORE_PORT
              value: "{{ .Values.hive.service.metastorePort }}"
            # HiveServer2
            - name: HIVE_SERVER2_HOST
              value: "0.0.0.0"
            - name: HIVE_SERVER2_BIND_HOST
              value: "0.0.0.0"
            - name: HIVE_SERVER2_PORT
              value: {{ .Values.hive.server2.port | quote }}
            - name: HIVE_SERVER2_AUTHENTICATION
              value: {{ .Values.hive.server2.authentication | quote }}
            - name: HIVE_SERVER2_SASL_ENABLED
              value: {{ .Values.hive.server2.sasl.enabled | quote }}
            - name: HIVE_SERVER2_SASL_QOP
              value: {{ .Values.hive.server2.sasl.qop | quote }}
            # Hive Directories
            - name: HIVE_WAREHOUSE_DIR
              value: "file:///opt/hive/warehouse"
            - name: HIVE_SCRATCH_DIR
              value: "file:///opt/hive/scratch"
            # Hive Logging
            - name: HIVE_LOG_LEVEL
              value: {{ .Values.hive.logging.level | quote }}
            # MinIO Configuration
            - name: MINIO_BUCKET
              value: {{ .Values.minio.bucket | quote }}
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "spark-arm.fullname" . }}-minio
                  key: access-key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "spark-arm.fullname" . }}-minio
                  key: secret-key
            - name: AWS_ENDPOINT_URL
              value: {{ .Values.minio.endpoint | quote }}
            {{- with .Values.hive.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          ports:
            - name: metastore
              containerPort: {{ .Values.hive.service.metastorePort }}
              protocol: TCP
            - name: server2
              containerPort: {{ .Values.hive.service.server2Port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.hive.resources | nindent 12 }}
          volumeMounts:
            - name: hive-logs
              mountPath: /opt/hive/logs
            - name: hive-warehouse
              mountPath: /opt/hive/warehouse
            - name: hive-scratch
              mountPath: /opt/hive/scratch
            - name: hadoop-libs
              mountPath: /opt/hadoop/lib
              subPath: lib
            - name: hadoop-conf
              mountPath: /opt/hadoop/etc/hadoop
              subPath: etc/hadoop
      volumes:
        - name: hive-logs
          persistentVolumeClaim:
            claimName: {{ include "spark-arm.fullname" . }}-hive-logs
        - name: hive-warehouse
          persistentVolumeClaim:
            claimName: {{ include "spark-arm.fullname" . }}-hive-warehouse
        - name: hive-scratch
          persistentVolumeClaim:
            claimName: {{ include "spark-arm.fullname" . }}-hive-scratch
        - name: hadoop-libs
          emptyDir: {}
        - name: hadoop-conf
          emptyDir: {}
      {{- with .Values.hive.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hive.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hive.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spark-arm.fullname" . }}-hive-logs
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: hive
spec:
  accessModes:
    - {{ .Values.hive.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.hive.persistence.size }}
  storageClassName: {{ .Values.hive.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spark-arm.fullname" . }}-hive-warehouse
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: hive
spec:
  accessModes:
    - {{ .Values.hive.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.hive.persistence.size }}
  storageClassName: {{ .Values.hive.persistence.storageClass }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spark-arm.fullname" . }}-hive-scratch
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: hive
spec:
  accessModes:
    - {{ .Values.hive.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.hive.persistence.size }}
  storageClassName: {{ .Values.hive.persistence.storageClass }} 