apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-arm.fullname" . }}-hive
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: hive
spec:
  type: {{ .Values.hive.service.type }}
  ports:
    - port: {{ .Values.hive.service.metastorePort }}
      targetPort: metastore
      protocol: TCP
      name: metastore
    - port: {{ .Values.hive.service.server2Port }}
      targetPort: server2
      protocol: TCP
      name: server2
  selector:
    {{- include "spark-arm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: hive 