apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-arm.fullname" . }}-hive
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: hive
type: Opaque
stringData:
  metastore-password: {{ .Values.hive.metastore.postgres.password }} 