apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-arm.fullname" . }}-hive
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: hive
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.hive.server2.port }}
      targetPort: thrift
      protocol: TCP
      name: thrift
  selector:
    {{- include "spark-arm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: hive 