{{- if .Values.minio.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-arm.fullname" . }}-minio-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.minio.credentials.accessKey | b64enc | quote }}
  secretKey: {{ .Values.minio.credentials.secretKey | b64enc | quote }}
{{- end }} 