apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spark-arm.fullname" . }}-minio
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: minio
type: Opaque
stringData:
  access-key: {{ .Values.minio.credentials.accessKey }}
  secret-key: {{ .Values.minio.credentials.secretKey }}
  s3a-access-key: {{ .Values.minio.credentials.accessKey }}
  s3a-secret-key: {{ .Values.minio.credentials.secretKey }} 