apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "spark-arm.fullname" . }}-logs-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/spark-logs"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "spark-arm.fullname" . }}-logs
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storage.className }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }} 