apiVersion: v1
kind: Secret
metadata:
  name: spark-arm-postgres
  labels:
    helm.sh/chart: spark-arm-1.0.0
    app.kubernetes.io/name: spark-arm
    app.kubernetes.io/instance: spark-arm
    app.kubernetes.io/version: "3.5.1"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  username: {{ .Values.postgres.user | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.database | quote }} 