apiVersion: v1
kind: Service
metadata:
  name: {{ include "spark-arm.fullname" . }}-master
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: master
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "spark-arm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: master
  ports:
    - name: spark
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
    - name: webui
      port: {{ .Values.service.uiPort }}
      targetPort: {{ .Values.service.uiPort }}