{{- if and .Values.traefik.enabled .Values.traefik.ssl.enabled }}
{{- if .Values.traefik.ssl.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: spark-tls
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ required "A valid .Values.traefik.ssl.cert entry required!" .Values.traefik.ssl.cert }}
  tls.key: {{ required "A valid .Values.traefik.ssl.key entry required!" .Values.traefik.ssl.key }}
{{- end }}

{{- if .Values.traefik.ssl.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: spark-tls
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
spec:
  secretName: spark-tls
  dnsNames:
    - {{ (index .Values.ingress.hosts 0).host }}
  issuerRef:
    name: {{ .Values.traefik.ssl.certManager.issuerName }}
    kind: {{ .Values.traefik.ssl.certManager.issuerKind }}
{{- end }}
{{- end }} 