{{- if and .Values.ingress.enabled .Values.traefik.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: spark-master-ui
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- if .Values.traefik.ssl.enabled }}
    - websecure
    {{- else }}
    - web
    {{- end }}
  routes:
    - match: Host(`{{ (index .Values.ingress.hosts 0).host }}`)
      kind: Rule
      services:
        - name: spark-master
          port: {{ .Values.service.uiPort }}
      middlewares:
        {{- if .Values.traefik.middlewares.auth.enabled }}
        - name: spark-auth
        {{- end }}
        {{- if .Values.traefik.middlewares.cors.enabled }}
        - name: spark-cors
        {{- end }}
        {{- if .Values.traefik.middlewares.rateLimit.enabled }}
        - name: spark-rate-limit
        {{- end }}
  {{- if .Values.traefik.ssl.enabled }}
  tls:
    {{- if .Values.traefik.ssl.existingSecret }}
    secretName: {{ .Values.traefik.ssl.existingSecret }}
    {{- else }}
    secretName: spark-tls
    {{- end }}
  {{- end }}
---
{{- if .Values.traefik.middlewares.auth.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: spark-auth
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
spec:
  basicAuth:
    secret: spark-auth-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: spark-auth-secret
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
type: Opaque
data:
  users: {{ .Values.traefik.middlewares.auth.users | toJson | b64enc }}
{{- end }}
---
{{- if .Values.traefik.middlewares.cors.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: spark-cors
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
spec:
  cors:
    allowedOrigins: {{ .Values.traefik.middlewares.cors.allowedOrigins | toJson }}
    allowedMethods: {{ .Values.traefik.middlewares.cors.allowedMethods | toJson }}
{{- end }}
---
{{- if .Values.traefik.middlewares.rateLimit.enabled }}
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: spark-rate-limit
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
spec:
  rateLimit:
    average: {{ .Values.traefik.middlewares.rateLimit.average }}
    burst: {{ .Values.traefik.middlewares.rateLimit.burst }}
{{- end }}
{{- end }} 