apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "spark-arm.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  serviceName: {{ include "spark-arm.fullname" . }}-worker
  # Set number of worker replicas from values.yaml
  replicas: {{ .Values.worker.replicaCount | default 1 }}
  selector:
    matchLabels:
      {{- include "spark-arm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "spark-arm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "spark-arm.serviceAccountName" . }}
      {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
        - name: spark-logs
          persistentVolumeClaim:
            claimName: {{ include "spark-arm.fullname" . }}-logs
      containers:
        - name: spark
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/opt/spark/bin/spark-class"]
          args: ["org.apache.spark.deploy.worker.Worker", "spark://{{ include "spark-arm.fullname" . }}-master:7077"]
          env:
            - name: SPARK_HOME
              value: /opt/spark
            - name: SPARK_NODE_TYPE
              value: "worker"
            - name: SPARK_LOCAL_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARK_PUBLIC_DNS
              value: {{ include "spark-arm.fullname" . }}-worker
            - name: SPARK_WORKER_OPTS
              value: >-
                -Dspark.worker.cleanup.enabled=true
                {{- if .Values.minio.enabled }}
                -Dspark.hadoop.fs.s3a.access.key=$(MINIO_ACCESS_KEY)
                -Dspark.hadoop.fs.s3a.secret.key=$(MINIO_SECRET_KEY)
                {{- end }}
                {{- if .Values.hive.enabled }}
                {{- range $key, $value := .Values.hive.spark.hadoop }}
                -D{{ $key }}={{ $value | quote }}
                {{- end }}
                {{- end }}
                {{- if .Values.delta.enabled }}
                {{- range $key, $value := .Values.delta.spark.hadoop }}
                -D{{ $key }}={{ $value | quote }}
                {{- end }}
                {{- end }}
            {{- if .Values.minio.enabled }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "spark-arm.fullname" . }}-minio-credentials
                  key: accessKey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "spark-arm.fullname" . }}-minio-credentials
                  key: secretKey
            {{- end }}
            {{- if .Values.hive.enabled }}
            - name: POSTGRES_HOST
              value: {{ .Values.hive.metastore.host | quote }}
            - name: POSTGRES_PORT
              value: {{ .Values.hive.metastore.port | quote }}
            - name: POSTGRES_DB
              value: {{ .Values.hive.metastore.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.hive.metastore.username | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.hive.metastore.password | quote }}
            - name: HIVE_METASTORE_HOST
              value: {{ .Values.hive.metastore.host | quote }}
            {{- end }}
            - name: SPARK_WORKER_CORES
              value: {{ .Values.worker.cores | quote }}
            - name: SPARK_WORKER_MEMORY
              value: {{ .Values.worker.memory | quote }}
            - name: SPARK_WORKER_WEBUI_PORT
              value: "8081"
            - name: SPARK_DAEMON_JAVA_OPTS
              value: "-Dspark.worker.cleanup.enabled=true"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: spark
            - containerPort: 8081
              name: webui
          volumeMounts:
            - name: spark-logs
              mountPath: /opt/spark/logs
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          startupProbe:
            tcpSocket:
              port: webui
            initialDelaySeconds: 10
            periodSeconds: 3
            failureThreshold: 30
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: webui
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: webui
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3 