apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "spark-arm.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "spark-arm.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  serviceName: {{ include "spark-arm.fullname" . }}-worker
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "spark-arm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "spark-arm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ include "spark-arm.serviceAccountName" . }}
      {{- end }}
      volumes:
        - name: spark-logs
          persistentVolumeClaim:
            claimName: {{ include "spark-arm.fullname" . }}-logs
      containers:
        - name: spark
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            # Minimal static env block (no templating) to avoid indentation issues.
            - name: SPARK_HOME
              value: /opt/spark
            - name: SPARK_NODE_TYPE
              value: "worker"
            - name: SPARK_MASTER_HOST
              value: "spark-master"
            - name: SPARK_LOCAL_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SPARK_PUBLIC_DNS
              value: {{ include "spark-arm.fullname" . }}-worker
          ports:
            - containerPort: {{ .Values.service.port }}
              name: spark
            - containerPort: {{ .Values.service.uiPort }}
              name: webui
          volumeMounts:
            - name: spark-logs
              mountPath: /opt/spark/logs
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
          startupProbe:
            tcpSocket:
              port: webui
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          livenessProbe:
            tcpSocket:
              port: webui
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: webui
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3 